# Generated by Django 4.2.3 on 2024-01-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True, verbose_name='nom chemin')),
                ('chemin', models.CharField(blank=True, max_length=100, null=True, verbose_name='chemin acces')),
            ],
        ),
    ]
